### ISSUE TITLE
You must change the version of the package Caporal

### ISSUE THREAD

**Issue by Barbapapazes** [fabiospampinato/bump#28]
git://github.com/fabiospampinato/Caporal.js.git because of this https://itsmycode.com/the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported/

**Comment by goofballtech** [comment]
agreed. Npm install fails on this error now.

**Comment by joshmeads** [comment]
100%. Blocks any install of this package on our organisations machines.

The comment on https://github.com/fabiospampinato/bump/issues/18#issuecomment-559529256 is incorrect. I personally am currently working from home (as in my team) none of us are using any proxies whatsoever. Simply using Yarn or PNPM this fails to install due to this error. Having people override their git config to fix a single package isn't a solid recommendation.

```
❯ yarn add @fabiospampinato/bump
➤ YN0000: ┌ Resolution step
➤ YN0001: │ caporal@git://github.com/fabiospampinato/Caporal.js.git#cf0f5eeefb2e04cc07798bf4a45d6bda5e2a2f63: Failed listing refs
➤ YN0001: │   Repository URL: git://github.com/fabiospampinato/Caporal.js.git
➤ YN0001: │   Fatal Error: unable to connect to github.com:
➤ YN0001: │   Github.com[0 Error: 140.82.113.3]: errno=Operation timed out
➤ YN0001: │   Exit Code: 128
➤ YN0000: └ Completed in 1m 20s
➤ YN0000: Failed with errors in 1m 20s
```

Forked and made that one change you dismissed:
```
yarn add bump@https://github.com/IntergalacticAgency/bump.git
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 3s 214ms
```
